- name: "Set env"
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items: "{{ environment }}"

- name: "install python."
  become: true
  apt:
    name: ["python3"]
    state: latest
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: no

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present