- name: copying file with playbook
  become: true 
  copy:
    src: ~/artifact.tar.gz
    dest: ~/

- name: "Unzip app"
  become: true
  unarchive:
    src: ~/artifact.tar.gz
    dest: ./
    

- name: "Start app"
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start