- name: copying file with playbook
  become: true 
  copy:
    src: ../../artifact.tar.gz
    dest: ~/

- name: "Unzip app"
  become: true
  unarchive:
    src: ~/artifact.tar.gz
    dest: ./
    remote_src: yes

- name: "Setup app"
  become: true
  shell: |
    npm install
    npm build

- name: "start server"
  become: true
  command: pm2 start -f main.js
  args:
    chdir: /home/ubuntu/dist
